// Generates a comprehensive MLB player dataset
// Each entry: { id, name, teams: [{team, positions[], seasons[]}] }
// Output format: flat array with one entry per player,
// teams[] = all teams played for, positions[] = all positions played, seasons[] = all seasons

// This dataset covers ~1980-2024 with real player data
// Positions: C, 1B, 2B, 3B, SS, LF, CF, RF, DH, SP, RP

const players = [
  // ─── CATCHERS ───────────────────────────────────────────────────────────
  { name: "Johnny Bench", teams: ["CIN"], positions: ["C"], seasons: range(1967,1983) },
  { name: "Carlton Fisk", teams: ["BOS","CHW"], positions: ["C"], seasons: range(1969,1993) },
  { name: "Gary Carter", teams: ["MON","NYM","SFG","LAD","MON"], positions: ["C"], seasons: range(1974,1992) },
  { name: "Mike Piazza", teams: ["LAD","FLA","NYM","SDP","OAK"], positions: ["C"], seasons: range(1992,2007) },
  { name: "Ivan Rodriguez", teams: ["TEX","FLA","DET","NYY","HOU","NYM","WSN","PHI"], positions: ["C"], seasons: range(1991,2011) },
  { name: "Yadier Molina", teams: ["STL"], positions: ["C"], seasons: range(2004,2022) },
  { name: "Joe Mauer", teams: ["MIN"], positions: ["C","1B"], seasons: range(2004,2018) },
  { name: "Buster Posey", teams: ["SFG"], positions: ["C","1B"], seasons: range(2009,2021) },
  { name: "Brian McCann", teams: ["ATL","NYY","HOU","TOR"], positions: ["C"], seasons: range(2005,2019) },
  { name: "J.T. Realmuto", teams: ["MIA","PHI"], positions: ["C"], seasons: range(2014,2024) },
  { name: "Salvador Perez", teams: ["KCR"], positions: ["C"], seasons: range(2011,2024) },
  { name: "Willson Contreras", teams: ["CHC","STL"], positions: ["C"], seasons: range(2016,2024) },
  { name: "Yasmani Grandal", teams: ["SDP","LAD","MIL","CHW"], positions: ["C","1B"], seasons: range(2012,2022) },
  { name: "Russell Martin", teams: ["LAD","PIT","NYY","TOR","LAD"], positions: ["C"], seasons: range(2006,2019) },
  { name: "Jason Varitek", teams: ["BOS"], positions: ["C"], seasons: range(1997,2011) },
  { name: "A.J. Pierzynski", teams: ["MIN","SFG","CHW","TEX","BOS","STL","ATL"], positions: ["C"], seasons: range(1998,2014) },
  { name: "Jorge Posada", teams: ["NYY"], positions: ["C"], seasons: range(1995,2011) },
  { name: "Victor Martinez", teams: ["CLE","BOS","DET"], positions: ["C","1B"], seasons: range(2002,2017) },
  { name: "Ryan Doumit", teams: ["PIT","MIN","ATL","NYM"], positions: ["C","OF","DH"], seasons: range(2005,2014) },
  { name: "Chris Iannetta", teams: ["COL","LAA","SEA","ARI","COL"], positions: ["C"], seasons: range(2006,2018) },
  { name: "Matt Wieters", teams: ["BAL","WSN","STL"], positions: ["C"], seasons: range(2009,2018) },
  { name: "Welington Castillo", teams: ["CHC","ARI","BAL","SEA","CHW"], positions: ["C"], seasons: range(2010,2019) },
  { name: "Wilson Ramos", teams: ["MIN","WSN","TBR","PHI","NYM","LAD"], positions: ["C"], seasons: range(2010,2020) },
  { name: "Gary Sanchez", teams: ["NYY","MIN"], positions: ["C"], seasons: range(2015,2022) },
  { name: "Roberto Perez", teams: ["CLE"], positions: ["C"], seasons: range(2014,2021) },
  { name: "Tucker Barnhart", teams: ["CIN","DET"], positions: ["C"], seasons: range(2014,2022) },
  { name: "Travis d'Arnaud", teams: ["NYM","LAD","TBR","ATL"], positions: ["C"], seasons: range(2013,2024) },
  { name: "Danny Jansen", teams: ["TOR"], positions: ["C"], seasons: range(2018,2024) },
  { name: "Sean Murphy", teams: ["OAK","ATL"], positions: ["C"], seasons: range(2019,2024) },
  { name: "Adley Rutschman", teams: ["BAL"], positions: ["C"], seasons: range(2022,2024) },
  { name: "Bo Diaz", teams: ["BOS","CLE","PHI","CIN"], positions: ["C"], seasons: range(1977,1989) },
  { name: "Terry Steinbach", teams: ["OAK","MIN"], positions: ["C"], seasons: range(1986,1999) },
  { name: "Sandy Alomar Jr.", teams: ["SDP","CLE","CHW","COL","TEX","NYM","CHW"], positions: ["C"], seasons: range(1988,2007) },
  { name: "Charles Johnson", teams: ["FLA","MIA","BAL","CHW","COL","FLA"], positions: ["C"], seasons: range(1994,2005) },
  { name: "Jason Kendall", teams: ["PIT","OAK","CHC","MIL","KCR"], positions: ["C"], seasons: range(1996,2010) },
  { name: "Brad Ausmus", teams: ["SDP","DET","HOU","LAD","HOU"], positions: ["C"], seasons: range(1993,2010) },
  { name: "Michael Barrett", teams: ["MON","CHC","SDP","BOS","TOR"], positions: ["C"], seasons: range(1998,2009) },
  { name: "Rod Barajas", teams: ["ARI","TEX","PHI","TOR","NYM","LAD","PIT"], positions: ["C"], seasons: range(1999,2012) },
  { name: "Geovany Soto", teams: ["CHC","TEX","OAK","CHW","LAA"], positions: ["C"], seasons: range(2005,2016) },
  { name: "Dioner Navarro", teams: ["LAD","TBR","SEA","CHC","TOR"], positions: ["C"], seasons: range(2004,2015) },
  { name: "Miguel Montero", teams: ["ARI","CHC","TOR","WSN"], positions: ["C"], seasons: range(2006,2017) },
  { name: "Nick Hundley", teams: ["SDP","COL","SFG","BAL"], positions: ["C"], seasons: range(2008,2018) },
  { name: "Luke Maile", teams: ["TBR","TOR","CIN","PIT"], positions: ["C"], seasons: range(2015,2022) },
  { name: "Yan Gomes", teams: ["CLE","WSN","OAK","CHC"], positions: ["C"], seasons: range(2012,2024) },
  { name: "Mike Zunino", teams: ["SEA","TBR","CLE"], positions: ["C"], seasons: range(2013,2022) },
  { name: "Omar Narvaez", teams: ["CHW","SEA","MIL","NYM"], positions: ["C"], seasons: range(2016,2023) },
  { name: "Christian Vazquez", teams: ["BOS","HOU","MIN","MIL"], positions: ["C"], seasons: range(2014,2024) },
  { name: "Tomas Nido", teams: ["NYM"], positions: ["C"], seasons: range(2017,2023) },
  { name: "Patrick Bailey", teams: ["SFG"], positions: ["C"], seasons: range(2023,2024) },
  { name: "William Contreras", teams: ["ATL","MIL"], positions: ["C"], seasons: range(2021,2024) },

  // ─── FIRST BASEMEN ────────────────────────────────────────────────────────
  { name: "Keith Hernandez", teams: ["STL","NYM","CLE"], positions: ["1B"], seasons: range(1974,1990) },
  { name: "Eddie Murray", teams: ["BAL","LAD","NYM","CLE","STL","ANA","CHC"], positions: ["1B","DH"], seasons: range(1977,1997) },
  { name: "Don Mattingly", teams: ["NYY"], positions: ["1B"], seasons: range(1982,1995) },
  { name: "Mark McGwire", teams: ["OAK","STL"], positions: ["1B"], seasons: range(1986,2001) },
  { name: "Jeff Bagwell", teams: ["HOU"], positions: ["1B"], seasons: range(1991,2005) },
  { name: "Frank Thomas", teams: ["CHW","OAK","TOR"], positions: ["1B","DH"], seasons: range(1990,2008) },
  { name: "Albert Pujols", teams: ["STL","LAA","LAD","KCR"], positions: ["1B"], seasons: range(2001,2022) },
  { name: "Jim Thome", teams: ["CLE","PHI","CHW","MIN","LAD"], positions: ["1B","DH"], seasons: range(1991,2012) },
  { name: "Todd Helton", teams: ["COL"], positions: ["1B"], seasons: range(1997,2013) },
  { name: "David Ortiz", teams: ["MIN","BOS"], positions: ["1B","DH"], seasons: range(1997,2016) },
  { name: "Ryan Howard", teams: ["PHI"], positions: ["1B"], seasons: range(2004,2016) },
  { name: "Prince Fielder", teams: ["MIL","DET","TEX"], positions: ["1B"], seasons: range(2005,2016) },
  { name: "Joey Votto", teams: ["CIN"], positions: ["1B"], seasons: range(2007,2023) },
  { name: "Paul Goldschmidt", teams: ["ARI","STL"], positions: ["1B"], seasons: range(2011,2024) },
  { name: "Freddie Freeman", teams: ["ATL","LAD"], positions: ["1B"], seasons: range(2010,2024) },
  { name: "Anthony Rizzo", teams: ["SDP","CHC","NYY"], positions: ["1B"], seasons: range(2011,2024) },
  { name: "Pete Alonso", teams: ["NYM"], positions: ["1B"], seasons: range(2019,2024) },
  { name: "Matt Olson", teams: ["OAK","ATL"], positions: ["1B"], seasons: range(2016,2024) },
  { name: "Vladimir Guerrero Jr.", teams: ["TOR"], positions: ["1B","3B"], seasons: range(2019,2024) },
  { name: "Nathaniel Lowe", teams: ["TBR","TEX"], positions: ["1B"], seasons: range(2019,2024) },
  { name: "Yuli Gurriel", teams: ["HOU","MIA"], positions: ["1B","3B"], seasons: range(2016,2023) },
  { name: "Carlos Santana", teams: ["CLE","PHI","KCR","SEA","MIN","MIL","PIT"], positions: ["1B","DH"], seasons: range(2010,2024) },
  { name: "Justin Smoak", teams: ["TEX","SEA","TOR","MIL"], positions: ["1B"], seasons: range(2010,2020) },
  { name: "Eric Hosmer", teams: ["KCR","SDP"], positions: ["1B"], seasons: range(2011,2022) },
  { name: "Brandon Belt", teams: ["SFG","TOR"], positions: ["1B"], seasons: range(2011,2023) },
  { name: "Lucas Duda", teams: ["NYM","KCR","TBR","ATL"], positions: ["1B"], seasons: range(2010,2019) },
  { name: "Mark Teixeira", teams: ["TEX","ATL","ANA","NYY"], positions: ["1B"], seasons: range(2003,2016) },
  { name: "Kendrys Morales", teams: ["ANA","SEA","MIN","KCR","TOR","OAK"], positions: ["1B","DH"], seasons: range(2006,2019) },
  { name: "Adam LaRoche", teams: ["ATL","PIT","ARI","BOS","WSN","CHW"], positions: ["1B"], seasons: range(2004,2015) },
  { name: "Lyle Overbay", teams: ["ARI","MIL","TOR","PIT","ARI","NYY","MIL"], positions: ["1B"], seasons: range(2001,2014) },
  { name: "James Loney", teams: ["LAD","BOS","NYM","TBR","SEA"], positions: ["1B"], seasons: range(2006,2017) },
  { name: "Ike Davis", teams: ["NYM","PIT","OAK"], positions: ["1B"], seasons: range(2010,2015) },
  { name: "Chris Davis", teams: ["TEX","BAL"], positions: ["1B","3B","OF"], seasons: range(2008,2019) },
  { name: "Mitch Moreland", teams: ["TEX","BOS","SDP","OAK"], positions: ["1B"], seasons: range(2010,2021) },
  { name: "C.J. Cron", teams: ["LAA","TBR","MIN","DET","COL"], positions: ["1B","DH"], seasons: range(2014,2024) },
  { name: "Jake Bauers", teams: ["TBR","CLE","SEA","NYY"], positions: ["1B","OF"], seasons: range(2018,2022) },
  { name: "Jose Abreu", teams: ["CHW","HOU"], positions: ["1B","DH"], seasons: range(2014,2023) },
  { name: "Yordan Alvarez", teams: ["HOU"], positions: ["LF","DH","1B"], seasons: range(2019,2024) },
  { name: "Spencer Torkelson", teams: ["DET"], positions: ["1B"], seasons: range(2022,2024) },
  { name: "Triston Casas", teams: ["BOS"], positions: ["1B"], seasons: range(2022,2024) },
  { name: "Will Myers", teams: ["KCR","TBR","SDP"], positions: ["RF","1B","DH"], seasons: range(2013,2022) },
  { name: "Wil Nieves", teams: ["NYY","MON","WSN","COL","MIL","ARI","ATL","PHI"], positions: ["C"], seasons: range(2000,2015) },
  { name: "Kent Hrbek", teams: ["MIN"], positions: ["1B"], seasons: range(1981,1994) },
  { name: "Rafael Palmeiro", teams: ["CHC","TEX","BAL","TEX"], positions: ["1B","DH"], seasons: range(1986,2005) },
  { name: "John Olerud", teams: ["TOR","NYM","SEA","NYY","BOS"], positions: ["1B"], seasons: range(1989,2005) },
  { name: "Andres Galarraga", teams: ["MON","STL","COL","ATL","TEX","SFG","ANA"], positions: ["1B"], seasons: range(1985,2004) },
  { name: "Mo Vaughn", teams: ["BOS","ANA","NYM"], positions: ["1B"], seasons: range(1991,2003) },
  { name: "Tino Martinez", teams: ["SEA","NYY","STL","TB"], positions: ["1B"], seasons: range(1990,2005) },
  { name: "Will Clark", teams: ["SFG","TEX","BAL","STL"], positions: ["1B"], seasons: range(1986,2000) },
  { name: "Cecil Fielder", teams: ["TOR","DET","NYY","ANA","CLE"], positions: ["1B","DH"], seasons: range(1985,1998) },

  // ─── SECOND BASEMEN ──────────────────────────────────────────────────────
  { name: "Ryne Sandberg", teams: ["PHI","CHC"], positions: ["2B"], seasons: range(1981,1997) },
  { name: "Roberto Alomar", teams: ["SDP","TOR","BAL","CLE","NYM","ARI","CHW"], positions: ["2B"], seasons: range(1988,2004) },
  { name: "Craig Biggio", teams: ["HOU"], positions: ["C","2B","CF"], seasons: range(1988,2007) },
  { name: "Jeff Kent", teams: ["TOR","NYM","CLE","SFG","HOU","LAD"], positions: ["2B"], seasons: range(1992,2008) },
  { name: "Jose Altuve", teams: ["HOU"], positions: ["2B"], seasons: range(2011,2024) },
  { name: "Robinson Cano", teams: ["NYY","SEA","NYM","ATL","CHW"], positions: ["2B"], seasons: range(2005,2023) },
  { name: "Dustin Pedroia", teams: ["BOS"], positions: ["2B"], seasons: range(2006,2019) },
  { name: "Ian Kinsler", teams: ["TEX","DET","LAA","BOS","SDP"], positions: ["2B"], seasons: range(2006,2019) },
  { name: "Ozzie Albies", teams: ["ATL"], positions: ["2B"], seasons: range(2017,2024) },
  { name: "DJ LeMahieu", teams: ["CHC","COL","NYY"], positions: ["2B","3B","1B"], seasons: range(2011,2024) },
  { name: "Whit Merrifield", teams: ["KCR","TOR","PHI"], positions: ["2B","RF"], seasons: range(2016,2024) },
  { name: "Kolten Wong", teams: ["STL","MIL","SEA"], positions: ["2B"], seasons: range(2013,2024) },
  { name: "Starlin Castro", teams: ["CHC","NYY","MIA","WSN"], positions: ["2B","SS"], seasons: range(2010,2020) },
  { name: "Daniel Murphy", teams: ["NYM","WSN","CHC","COL"], positions: ["2B","1B"], seasons: range(2008,2019) },
  { name: "Ben Zobrist", teams: ["HOU","TBR","OAK","KCR","CHC"], positions: ["2B","SS","RF","LF"], seasons: range(2006,2019) },
  { name: "Chase Utley", teams: ["PHI","LAD"], positions: ["2B"], seasons: range(2003,2018) },
  { name: "Brandon Phillips", teams: ["CLE","CIN","ATL","LAA"], positions: ["2B"], seasons: range(2002,2018) },
  { name: "Howie Kendrick", teams: ["LAA","LAD","ARI","PHI","WSN"], positions: ["2B","OF","1B"], seasons: range(2006,2020) },
  { name: "Aaron Hill", teams: ["TOR","ARI","MIL","BOS","SFG"], positions: ["2B","3B"], seasons: range(2005,2018) },
  { name: "Gordon Beckham", teams: ["CHW","LAA","ATL","DET","SFG","MIL"], positions: ["2B","SS"], seasons: range(2009,2018) },
  { name: "Darwin Barney", teams: ["CHC","LAD","TOR","NYY"], positions: ["2B"], seasons: range(2010,2017) },
  { name: "Jedd Gyorko", teams: ["SDP","STL","LAD","NYY","MIL"], positions: ["2B","3B","SS"], seasons: range(2013,2019) },
  { name: "Josh Harrison", teams: ["CHC","PIT","DET","PHI","OAK","WSN"], positions: ["2B","3B","OF"], seasons: range(2011,2022) },
  { name: "Scooter Gennett", teams: ["MIL","CIN","SFG","CLE"], positions: ["2B"], seasons: range(2013,2019) },
  { name: "Jonathan Schoop", teams: ["BAL","MIL","MIN","DET","CHC"], positions: ["2B","1B"], seasons: range(2013,2024) },
  { name: "Rougned Odor", teams: ["TEX","NYY","BAL"], positions: ["2B"], seasons: range(2014,2022) },
  { name: "Yoan Moncada", teams: ["BOS","CHW"], positions: ["2B","3B"], seasons: range(2016,2024) },
  { name: "Luis Arraez", teams: ["MIN","MIA","SDP"], positions: ["2B","1B","3B"], seasons: range(2019,2024) },
  { name: "Gleyber Torres", teams: ["NYY"], positions: ["SS","2B"], seasons: range(2018,2024) },
  { name: "Marcus Semien", teams: ["CHW","OAK","TOR","TEX"], positions: ["SS","2B"], seasons: range(2013,2024) },
  { name: "Lou Whitaker", teams: ["DET"], positions: ["2B"], seasons: range(1977,1995) },
  { name: "Bret Boone", teams: ["SEA","ATL","CIN","NYY","MIN"], positions: ["2B"], seasons: range(1992,2006) },
  { name: "Bip Roberts", teams: ["SDP","CIN","SDP","MIL","KCR","CLE"], positions: ["2B","OF"], seasons: range(1986,1998) },
  { name: "Delino DeShields", teams: ["MON","LAD","STL","BAL","CHC"], positions: ["2B"], seasons: range(1990,2002) },
  { name: "Marlon Anderson", teams: ["PHI","TBR","NYM","STL","WSN","LAD","NYM"], positions: ["2B"], seasons: range(1998,2009) },
  { name: "Adam Kennedy", teams: ["STL","ANA","SEA","WSN","OAK","CHW"], positions: ["2B"], seasons: range(1999,2011) },
  { name: "Mark Grudzielanek", teams: ["MON","LAD","CHC","STL","KCR"], positions: ["2B"], seasons: range(1995,2009) },
  { name: "Placido Polanco", teams: ["STL","PHI","DET","MIA"], positions: ["2B","3B"], seasons: range(1998,2013) },
  { name: "Orlando Hudson", teams: ["TOR","ARI","LAD","MIN","CHW","SDP","PHI"], positions: ["2B"], seasons: range(2002,2012) },
  { name: "Mark Ellis", teams: ["OAK","KCR","COL","LAD","STL"], positions: ["2B"], seasons: range(2002,2014) },
  { name: "Kelly Johnson", teams: ["ATL","ARI","TOR","NYY","BOS","NYM","BAL","TBR"], positions: ["2B","3B","OF"], seasons: range(2005,2017) },
  { name: "Ryan Theriot", teams: ["CHC","STL","SFG","LAD"], positions: ["2B","SS"], seasons: range(2005,2012) },

  // ─── THIRD BASEMEN ───────────────────────────────────────────────────────
  { name: "Mike Schmidt", teams: ["PHI"], positions: ["3B"], seasons: range(1972,1989) },
  { name: "Wade Boggs", teams: ["BOS","NYY","TBR"], positions: ["3B"], seasons: range(1982,1999) },
  { name: "George Brett", teams: ["KCR"], positions: ["3B","1B","DH"], seasons: range(1973,1993) },
  { name: "Chipper Jones", teams: ["ATL"], positions: ["3B","SS","LF"], seasons: range(1993,2012) },
  { name: "Scott Rolen", teams: ["PHI","STL","TOR","CIN"], positions: ["3B"], seasons: range(1996,2012) },
  { name: "Alex Rodriguez", teams: ["SEA","TEX","NYY"], positions: ["SS","3B"], seasons: range(1994,2016) },
  { name: "Nolan Arenado", teams: ["COL","STL"], positions: ["3B"], seasons: range(2013,2024) },
  { name: "Adrian Beltre", teams: ["LAD","SEA","BOS","TEX"], positions: ["3B"], seasons: range(1998,2018) },
  { name: "Evan Longoria", teams: ["TBR","SFG"], positions: ["3B"], seasons: range(2008,2023) },
  { name: "Ryan Zimmerman", teams: ["WSN"], positions: ["3B","1B"], seasons: range(2005,2021) },
  { name: "Josh Donaldson", teams: ["OAK","TOR","CLE","ATL","MIN","NYY"], positions: ["3B"], seasons: range(2010,2022) },
  { name: "Kris Bryant", teams: ["CHC","SFG","COL","TEX"], positions: ["3B","OF","1B"], seasons: range(2015,2024) },
  { name: "Austin Riley", teams: ["ATL"], positions: ["3B","OF"], seasons: range(2019,2024) },
  { name: "Rafael Devers", teams: ["BOS"], positions: ["3B"], seasons: range(2017,2024) },
  { name: "Matt Chapman", teams: ["OAK","TOR","SFG"], positions: ["3B"], seasons: range(2017,2024) },
  { name: "Jose Ramirez", teams: ["CLE"], positions: ["3B","2B"], seasons: range(2013,2024) },
  { name: "Anthony Rendon", teams: ["WSN","LAA"], positions: ["3B"], seasons: range(2013,2023) },
  { name: "Eugenio Suarez", teams: ["DET","CIN","SEA","ARI"], positions: ["3B","SS"], seasons: range(2014,2024) },
  { name: "Manny Machado", teams: ["BAL","LAD","SDP"], positions: ["3B","SS"], seasons: range(2012,2024) },
  { name: "Miguel Cabrera", teams: ["FLA","MIA","DET"], positions: ["1B","3B","RF"], seasons: range(2003,2023) },
  { name: "Pablo Sandoval", teams: ["SFG","BOS","ATL"], positions: ["3B","1B"], seasons: range(2008,2021) },
  { name: "David Wright", teams: ["NYM"], positions: ["3B"], seasons: range(2004,2018) },
  { name: "Chase Headley", teams: ["SDP","NYY","SDP"], positions: ["3B"], seasons: range(2007,2018) },
  { name: "Matt Carpenter", teams: ["STL","NYY","SDP"], positions: ["3B","2B","1B"], seasons: range(2011,2022) },
  { name: "Kevin Youkilis", teams: ["BOS","CHW","NYY"], positions: ["1B","3B"], seasons: range(2004,2013) },
  { name: "Aramis Ramirez", teams: ["PIT","CHC","MIL"], positions: ["3B"], seasons: range(1998,2015) },
  { name: "Troy Glaus", teams: ["ANA","ARI","TOR","STL"], positions: ["3B"], seasons: range(1998,2010) },
  { name: "Eric Chavez", teams: ["OAK","NYY","ARI","STL"], positions: ["3B"], seasons: range(1998,2014) },
  { name: "Vinny Castilla", teams: ["COL","ATL","TBR","HOU","WSN","SDP"], positions: ["3B"], seasons: range(1991,2006) },
  { name: "Terry Pendleton", teams: ["STL","ATL","FLA","CIN","KCR"], positions: ["3B"], seasons: range(1984,1998) },
  { name: "Dean Palmer", teams: ["TEX","KCR","DET"], positions: ["3B"], seasons: range(1989,2003) },
  { name: "Robin Ventura", teams: ["CHW","NYM","NYY","LAD"], positions: ["3B"], seasons: range(1989,2004) },
  { name: "Todd Zeile", teams: ["STL","CHC","PHI","BAL","LAD","FLA","NYM","TEX","COL","MON","NYY"], positions: ["3B","1B","C"], seasons: range(1989,2004) },
  { name: "Gary Gaetti", teams: ["MIN","KCR","STL","CHC","BOS"], positions: ["3B"], seasons: range(1981,2000) },
  { name: "Carney Lansford", teams: ["CAL","BOS","OAK"], positions: ["3B"], seasons: range(1978,1992) },
  { name: "Bill Madlock", teams: ["TEX","CHC","SFG","PIT","LAD","DET","STL"], positions: ["3B"], seasons: range(1973,1987) },

  // ─── SHORTSTOPS ──────────────────────────────────────────────────────────
  { name: "Cal Ripken Jr.", teams: ["BAL"], positions: ["SS","3B"], seasons: range(1981,2001) },
  { name: "Derek Jeter", teams: ["NYY"], positions: ["SS"], seasons: range(1995,2014) },
  { name: "Ozzie Smith", teams: ["SDP","STL"], positions: ["SS"], seasons: range(1978,1996) },
  { name: "Alan Trammell", teams: ["DET"], positions: ["SS"], seasons: range(1977,1996) },
  { name: "Barry Larkin", teams: ["CIN"], positions: ["SS"], seasons: range(1986,2004) },
  { name: "Nomar Garciaparra", teams: ["BOS","CHC","LAD","OAK"], positions: ["SS"], seasons: range(1996,2009) },
  { name: "Miguel Tejada", teams: ["OAK","BAL","HOU","SDP","SFG","KCR"], positions: ["SS"], seasons: range(1997,2013) },
  { name: "Jimmy Rollins", teams: ["PHI","LAD","CHW"], positions: ["SS"], seasons: range(2000,2016) },
  { name: "Jose Reyes", teams: ["NYM","MIA","TOR","NYM","COL"], positions: ["SS"], seasons: range(2003,2018) },
  { name: "Francisco Lindor", teams: ["CLE","NYM"], positions: ["SS"], seasons: range(2015,2024) },
  { name: "Corey Seager", teams: ["LAD","TEX"], positions: ["SS"], seasons: range(2015,2024) },
  { name: "Trea Turner", teams: ["SDP","WSN","LAD","PHI"], positions: ["SS","2B"], seasons: range(2015,2024) },
  { name: "Carlos Correa", teams: ["HOU","MIN","SFG"], positions: ["SS"], seasons: range(2015,2024) },
  { name: "Xander Bogaerts", teams: ["BOS","SDP"], positions: ["SS"], seasons: range(2013,2024) },
  { name: "Trevor Story", teams: ["COL","BOS"], positions: ["SS"], seasons: range(2016,2024) },
  { name: "Javier Baez", teams: ["CHC","NYM","DET"], positions: ["SS","2B","3B"], seasons: range(2014,2024) },
  { name: "Bobby Witt Jr.", teams: ["KCR"], positions: ["SS"], seasons: range(2022,2024) },
  { name: "Gunnar Henderson", teams: ["BAL"], positions: ["SS","3B"], seasons: range(2022,2024) },
  { name: "Wander Franco", teams: ["TBR"], positions: ["SS"], seasons: range(2021,2023) },
  { name: "CJ Abrams", teams: ["SDP","WSN"], positions: ["SS"], seasons: range(2022,2024) },
  { name: "Anthony Volpe", teams: ["NYY"], positions: ["SS"], seasons: range(2023,2024) },
  { name: "Bo Bichette", teams: ["TOR"], positions: ["SS"], seasons: range(2019,2024) },
  { name: "JP Crawford", teams: ["PHI","SEA"], positions: ["SS"], seasons: range(2017,2024) },
  { name: "Ha-seong Kim", teams: ["SDP"], positions: ["SS","2B","3B"], seasons: range(2021,2024) },
  { name: "Dansby Swanson", teams: ["ATL","CHC"], positions: ["SS"], seasons: range(2016,2024) },
  { name: "Hanley Ramirez", teams: ["FLA","MIA","LAD","BOS"], positions: ["SS","3B","LF"], seasons: range(2005,2018) },
  { name: "Jhonny Peralta", teams: ["CLE","DET","STL"], positions: ["SS","3B"], seasons: range(2003,2017) },
  { name: "Edgar Renteria", teams: ["FLA","STL","BOS","ATL","DET","CIN","SFG"], positions: ["SS"], seasons: range(1996,2011) },
  { name: "Jose Vizcaino", teams: ["LAD","CHC","NYM","CLE","TEX","SFG","HOU","NYY","STL"], positions: ["SS","2B","3B"], seasons: range(1989,2006) },
  { name: "Royce Clayton", teams: ["SFG","STL","TEX","CHW","ARI","COL","MIL","WSN","BOS","TOR"], positions: ["SS"], seasons: range(1991,2007) },
  { name: "Mark Grudzielanek", teams: ["MON","LAD","CHC","STL","KCR"], positions: ["2B","SS"], seasons: range(1995,2009) },
  { name: "Tony Fernandez", teams: ["TOR","SDP","NYM","CIN","CLE","NYY","MIL"], positions: ["SS"], seasons: range(1983,2001) },
  { name: "Ozzie Guillen", teams: ["CHW","BAL","ATL","TBR"], positions: ["SS"], seasons: range(1985,2000) },
  { name: "Rey Ordonez", teams: ["NYM","TBR","CHC"], positions: ["SS"], seasons: range(1996,2004) },
  { name: "Omar Vizquel", teams: ["SEA","CLE","SFG","TEX","CHW","TOR","CHC","MIA"], positions: ["SS"], seasons: range(1989,2012) },
  { name: "Rich Aurilia", teams: ["SFG","CIN","SEA","SDP","SFG"], positions: ["SS","2B"], seasons: range(1995,2009) },
  { name: "Alex Cora", teams: ["LAD","BOS","SEA","NYM","WSN"], positions: ["SS","2B"], seasons: range(1998,2009) },
  { name: "Rafael Furcal", teams: ["ATL","LAD","STL","MIA"], positions: ["SS"], seasons: range(2000,2014) },
  { name: "Stephen Drew", teams: ["ARI","OAK","BOS","NYY","WSN"], positions: ["SS"], seasons: range(2006,2016) },
  { name: "Erick Aybar", teams: ["LAA","ATL","DET","SDP"], positions: ["SS"], seasons: range(2006,2017) },
  { name: "Aledmys Diaz", teams: ["STL","TOR","HOU","OAK"], positions: ["SS","2B","3B"], seasons: range(2016,2022) },
  { name: "Didi Gregorius", teams: ["ARI","NYY","PHI"], positions: ["SS"], seasons: range(2012,2021) },
  { name: "Elvis Andrus", teams: ["TEX","OAK","CHW"], positions: ["SS"], seasons: range(2009,2022) },
  { name: "Alcides Escobar", teams: ["MIL","KCR","WSN","OAK"], positions: ["SS"], seasons: range(2008,2022) },
  { name: "Jose Iglesias", teams: ["BOS","DET","CIN","BAL","NYM","LAA","COL","PHI"], positions: ["SS"], seasons: range(2011,2022) },
  { name: "Jordy Mercer", teams: ["PIT","DET","STL"], positions: ["SS"], seasons: range(2012,2020) },
  { name: "Tim Anderson", teams: ["CHW"], positions: ["SS"], seasons: range(2016,2024) },
  { name: "Jorge Polanco", teams: ["MIN","SEA"], positions: ["SS","2B"], seasons: range(2014,2024) },
  { name: "Andrelton Simmons", teams: ["ATL","LAA","MIN","CHC"], positions: ["SS"], seasons: range(2012,2021) },
  { name: "Paul DeJong", teams: ["STL","TOR","CHW","SFG"], positions: ["SS"], seasons: range(2017,2024) },

  // ─── LEFT FIELDERS ───────────────────────────────────────────────────────
  { name: "Barry Bonds", teams: ["PIT","SFG"], positions: ["LF","RF"], seasons: range(1986,2007) },
  { name: "Rickey Henderson", teams: ["OAK","NYY","TOR","SDP","ANA","OAK","NYM","SEA","BOS","LAD","OAK"], positions: ["LF"], seasons: range(1979,2003) },
  { name: "Tim Raines", teams: ["MON","CHW","NYY","OAK","FLA","TBR"], positions: ["LF"], seasons: range(1979,2002) },
  { name: "Lou Brock", teams: ["CHC","STL"], positions: ["LF"], seasons: range(1961,1979) },
  { name: "Manny Ramirez", teams: ["CLE","BOS","LAD","CHW","TBR"], positions: ["LF","DH"], seasons: range(1993,2011) },
  { name: "Ryan Braun", teams: ["MIL"], positions: ["LF","RF"], seasons: range(2007,2021) },
  { name: "Christian Yelich", teams: ["MIA","MIL"], positions: ["LF","CF","RF"], seasons: range(2013,2024) },
  { name: "Yordan Alvarez", teams: ["HOU"], positions: ["LF","DH"], seasons: range(2019,2024) },
  { name: "Juan Soto", teams: ["WSN","SDP","NYY","NYM"], positions: ["LF","RF"], seasons: range(2018,2024) },
  { name: "Kyle Schwarber", teams: ["CHC","WSN","BOS","PHI"], positions: ["LF"], seasons: range(2015,2024) },
  { name: "Marcell Ozuna", teams: ["MIA","STL","ATL"], positions: ["LF","RF"], seasons: range(2013,2024) },
  { name: "Adam Dunn", teams: ["CIN","ARI","WSN","CHW","OAK"], positions: ["LF","1B"], seasons: range(2001,2014) },
  { name: "Alfonso Soriano", teams: ["NYY","TEX","CHC","WSN","NYY"], positions: ["LF","2B","RF"], seasons: range(1999,2014) },
  { name: "Raul Ibanez", teams: ["SEA","KCR","PHI","NYY","LAA","SEA"], positions: ["LF","DH"], seasons: range(1996,2014) },
  { name: "Pat Burrell", teams: ["PHI","TBR","SFG"], positions: ["LF"], seasons: range(2000,2011) },
  { name: "Bobby Abreu", teams: ["HOU","PHI","NYY","LAA","SFG","NYM"], positions: ["RF","LF"], seasons: range(1996,2012) },
  { name: "Jason Bay", teams: ["PIT","BOS","NYM","SEA"], positions: ["LF"], seasons: range(2003,2013) },
  { name: "Carl Crawford", teams: ["TBR","BOS","LAD"], positions: ["LF","CF"], seasons: range(2002,2016) },
  { name: "Matt Holliday", teams: ["COL","OAK","STL","NYY"], positions: ["LF"], seasons: range(2004,2018) },
  { name: "Chris Coghlan", teams: ["FLA","MIA","OAK","CHC","PIT","TOR"], positions: ["LF","2B"], seasons: range(2009,2017) },
  { name: "Nate McLouth", teams: ["PIT","ATL","BAL","WSN"], positions: ["CF","LF"], seasons: range(2005,2014) },
  { name: "Jonny Gomes", teams: ["TBR","CIN","OAK","BOS","WSN","KCR","ATL"], positions: ["LF","RF"], seasons: range(2003,2015) },
  { name: "Seth Smith", teams: ["COL","OAK","SDP","SEA","BAL"], positions: ["LF","RF"], seasons: range(2007,2017) },
  { name: "Alex Gordon", teams: ["KCR"], positions: ["LF","3B"], seasons: range(2007,2020) },
  { name: "Yoenis Cespedes", teams: ["OAK","BOS","DET","NYM"], positions: ["LF","CF"], seasons: range(2012,2020) },
  { name: "Corey Dickerson", teams: ["COL","TBR","PIT","PHI","STL","MIA"], positions: ["LF","RF"], seasons: range(2013,2021) },
  { name: "Justin Upton", teams: ["ARI","ATL","SDP","DET","LAA"], positions: ["RF","LF"], seasons: range(2007,2020) },
  { name: "Melky Cabrera", teams: ["NYY","KCR","ATL","SFG","TOR","CHW","CLE"], positions: ["CF","LF","RF"], seasons: range(2005,2017) },
  { name: "Martin Prado", teams: ["ATL","ARI","NYY","MIA"], positions: ["LF","3B","2B"], seasons: range(2006,2018) },
  { name: "Andre Ethier", teams: ["LAD"], positions: ["RF","LF"], seasons: range(2006,2017) },
  { name: "Marlon Byrd", teams: ["PHI","TEX","CHC","NYM","SFG","PIT","CIN"], positions: ["CF","RF","LF"], seasons: range(2002,2016) },
  { name: "Brennan Boesch", teams: ["DET","NYY","ANA","CIN"], positions: ["RF","LF"], seasons: range(2010,2014) },
  { name: "Carlos Lee", teams: ["CHW","MIL","TEX","HOU","MIA"], positions: ["LF"], seasons: range(1999,2012) },
  { name: "Geoff Jenkins", teams: ["MIL","PHI"], positions: ["LF"], seasons: range(1998,2008) },
  { name: "Garret Anderson", teams: ["CAL","ANA","LAA","ATL"], positions: ["LF","DH"], seasons: range(1994,2010) },
  { name: "Kevin McReynolds", teams: ["SDP","NYM","KCR","NYM"], positions: ["LF","CF"], seasons: range(1983,1994) },
  { name: "Dante Bichette", teams: ["CAL","MIL","COL","CIN","BOS"], positions: ["LF","RF"], seasons: range(1988,2001) },
  { name: "Jim Eisenreich", teams: ["MIN","KCR","MIL","PHI","FLA","LAD"], positions: ["RF","LF","CF"], seasons: range(1982,1998) },
  { name: "Luis Gonzalez", teams: ["HOU","CHC","DET","ARI","LAD","FLA"], positions: ["LF","1B"], seasons: range(1990,2008) },
  { name: "Brian Giles", teams: ["CLE","PIT","SDP"], positions: ["RF","LF"], seasons: range(1995,2009) },
  { name: "Cliff Floyd", teams: ["MON","FLA","NYM","CHC","COL","TBR"], positions: ["LF","1B"], seasons: range(1993,2009) },
  { name: "Hideki Matsui", teams: ["NYY","LAA","OAK","TBR"], positions: ["LF","DH"], seasons: range(2003,2012) },

  // ─── CENTER FIELDERS ─────────────────────────────────────────────────────
  { name: "Ken Griffey Jr.", teams: ["SEA","CIN","CHW"], positions: ["CF"], seasons: range(1989,2010) },
  { name: "Mike Trout", teams: ["LAA"], positions: ["CF","DH"], seasons: range(2011,2024) },
  { name: "Willie Mays", teams: ["NY1","SFG","NYM"], positions: ["CF"], seasons: range(1951,1973) },
  { name: "Ichiro Suzuki", teams: ["SEA","NYY","MIA"], positions: ["RF","CF"], seasons: range(2001,2019) },
  { name: "Andruw Jones", teams: ["ATL","LAD","TEX","CHW","NYY","STL","CIN"], positions: ["CF","RF"], seasons: range(1996,2012) },
  { name: "Jim Edmonds", teams: ["CAL","ANA","STL","SDP","CHC","MIL","CIN"], positions: ["CF"], seasons: range(1993,2010) },
  { name: "Kirby Puckett", teams: ["MIN"], positions: ["CF","RF"], seasons: range(1984,1995) },
  { name: "Andrew McCutchen", teams: ["PIT","SFG","NYY","PHI","MIL"], positions: ["CF","RF","LF"], seasons: range(2009,2024) },
  { name: "Carlos Beltran", teams: ["KCR","HOU","NYM","SFG","STL","NYY","TEX"], positions: ["CF","RF"], seasons: range(1998,2017) },
  { name: "Torii Hunter", teams: ["MIN","ANA","LAA","DET"], positions: ["CF","RF"], seasons: range(1997,2015) },
  { name: "Jacoby Ellsbury", teams: ["BOS","NYY"], positions: ["CF","LF"], seasons: range(2007,2017) },
  { name: "Curtis Granderson", teams: ["DET","NYY","NYM","LAD","MIL","TOR"], positions: ["CF","LF","RF"], seasons: range(2004,2018) },
  { name: "Grady Sizemore", teams: ["CLE","BOS","PHI","TBR"], positions: ["CF"], seasons: range(2004,2015) },
  { name: "Vernon Wells", teams: ["TOR","LAA","NYY"], positions: ["CF"], seasons: range(1999,2013) },
  { name: "Coco Crisp", teams: ["CLE","BOS","KCR","OAK","CLE"], positions: ["CF","LF"], seasons: range(2002,2016) },
  { name: "Adam Jones", teams: ["SEA","BAL","ARI","PHI","NYM"], positions: ["CF","RF"], seasons: range(2006,2020) },
  { name: "Lorenzo Cain", teams: ["MIL","KCR","MIL"], positions: ["CF"], seasons: range(2010,2021) },
  { name: "Dexter Fowler", teams: ["COL","HOU","CHC","STL","LAA"], positions: ["CF"], seasons: range(2008,2020) },
  { name: "Brett Gardner", teams: ["NYY"], positions: ["CF","LF"], seasons: range(2008,2021) },
  { name: "Rajai Davis", teams: ["SFG","OAK","TOR","DET","CLE","BOS","NYM","OAK"], positions: ["CF","LF","RF"], seasons: range(2006,2018) },
  { name: "Billy Hamilton", teams: ["CIN","KCR","SFG","ATL"], positions: ["CF"], seasons: range(2013,2020) },
  { name: "Ender Inciarte", teams: ["ARI","ATL"], positions: ["CF","LF"], seasons: range(2014,2021) },
  { name: "Kevin Pillar", teams: ["TOR","SFG","COL","BOS","NYM","LAD"], positions: ["CF","RF"], seasons: range(2013,2022) },
  { name: "Jon Jay", teams: ["STL","SDP","CHC","ARI","KCR","CHW"], positions: ["CF","LF","RF"], seasons: range(2010,2019) },
  { name: "Jarrod Dyson", teams: ["KCR","SEA","ARI","PIT","CHW"], positions: ["CF","LF"], seasons: range(2010,2021) },
  { name: "George Springer", teams: ["HOU","TOR"], positions: ["CF","RF"], seasons: range(2014,2024) },
  { name: "Kevin Kiermaier", teams: ["TBR","TOR"], positions: ["CF"], seasons: range(2013,2024) },
  { name: "Starling Marte", teams: ["PIT","ARI","MIA","OAK","NYM","SDP"], positions: ["CF","RF","LF"], seasons: range(2012,2024) },
  { name: "Julio Rodriguez", teams: ["SEA"], positions: ["CF"], seasons: range(2022,2024) },
  { name: "Corbin Carroll", teams: ["ARI"], positions: ["CF","LF","RF"], seasons: range(2022,2024) },
  { name: "Cedric Mullins", teams: ["BAL"], positions: ["CF"], seasons: range(2018,2024) },
  { name: "Daulton Varsho", teams: ["ARI","TOR","ATL"], positions: ["CF","C","LF"], seasons: range(2021,2024) },
  { name: "Michael Taylor", teams: ["WSN","KCR","MIN"], positions: ["CF"], seasons: range(2014,2024) },
  { name: "Alex Kirilloff", teams: ["MIN"], positions: ["LF","RF","1B"], seasons: range(2020,2024) },
  { name: "Bernie Williams", teams: ["NYY"], positions: ["CF","RF"], seasons: range(1991,2006) },
  { name: "Kenny Lofton", teams: ["HOU","CLE","ATL","CHW","SFG","PIT","CHC","NYY","PHI","LAD"], positions: ["CF"], seasons: range(1991,2007) },
  { name: "Johnny Damon", teams: ["KCR","OAK","BOS","NYY","DET","TBR","CLE"], positions: ["CF","LF"], seasons: range(1995,2012) },
  { name: "Devon White", teams: ["CAL","TOR","FLA","ARI","LAD","MIL"], positions: ["CF"], seasons: range(1985,2001) },
  { name: "Steve Finley", teams: ["BAL","HOU","SDP","ARI","LAD","SFG","COL"], positions: ["CF","LF"], seasons: range(1989,2007) },
  { name: "Lance Johnson", teams: ["STL","CHW","NYM","CHC","OAK"], positions: ["CF"], seasons: range(1987,2000) },
  { name: "Darryl Hamilton", teams: ["MIL","TEX","SFG","COL","NYM"], positions: ["CF","LF","RF"], seasons: range(1988,2001) },
  { name: "Lenny Dykstra", teams: ["NYM","PHI"], positions: ["CF"], seasons: range(1985,1996) },
  { name: "Brett Butler", teams: ["ATL","CLE","SFG","LAD","NYM","LAD"], positions: ["CF"], seasons: range(1981,1997) },
  { name: "Willie Wilson", teams: ["KCR","OAK","CHC"], positions: ["CF","LF"], seasons: range(1976,1994) },

  // ─── RIGHT FIELDERS ──────────────────────────────────────────────────────
  { name: "Hank Aaron", teams: ["MIL","ATL"], positions: ["RF","LF"], seasons: range(1954,1976) },
  { name: "Frank Robinson", teams: ["CIN","BAL","LAD","CAL","CLE"], positions: ["RF","LF","DH"], seasons: range(1956,1976) },
  { name: "Reggie Jackson", teams: ["KCR","OAK","BAL","NYY","CAL"], positions: ["RF","DH"], seasons: range(1967,1987) },
  { name: "Tony Gwynn", teams: ["SDP"], positions: ["RF","CF"], seasons: range(1982,2001) },
  { name: "Larry Walker", teams: ["MON","COL","STL"], positions: ["RF"], seasons: range(1989,2005) },
  { name: "Vladimir Guerrero", teams: ["MON","ANA","LAA","TEX","BAL","TOR"], positions: ["RF","DH"], seasons: range(1996,2011) },
  { name: "Mookie Betts", teams: ["BOS","LAD"], positions: ["RF","CF","2B"], seasons: range(2014,2024) },
  { name: "Bryce Harper", teams: ["WSN","PHI"], positions: ["RF","LF","1B"], seasons: range(2012,2024) },
  { name: "Giancarlo Stanton", teams: ["FLA","MIA","NYY"], positions: ["RF","LF","DH"], seasons: range(2010,2024) },
  { name: "Nick Markakis", teams: ["BAL","ATL"], positions: ["RF","LF"], seasons: range(2006,2020) },
  { name: "Jay Bruce", teams: ["CIN","NYM","CLE","SEA","PHI"], positions: ["RF","LF"], seasons: range(2008,2020) },
  { name: "Jose Bautista", teams: ["PIT","BAL","KCR","TBR","TOR","NYM","PHI","OAK","ATL"], positions: ["RF","3B","LF"], seasons: range(2004,2018) },
  { name: "Hunter Pence", teams: ["HOU","PHI","SFG","TEX"], positions: ["RF","CF","LF"], seasons: range(2007,2020) },
  { name: "Nelson Cruz", teams: ["MIL","TEX","BAL","SEA","MIN","TBR","WSN","SDP"], positions: ["RF","DH"], seasons: range(2005,2022) },
  { name: "Jayson Werth", teams: ["TOR","LAD","PHI","WSN"], positions: ["RF","CF"], seasons: range(2002,2017) },
  { name: "Shin-Soo Choo", teams: ["SEA","CLE","CIN","TEX","HOU"], positions: ["RF","CF","LF"], seasons: range(2005,2020) },
  { name: "Jeff Francoeur", teams: ["ATL","NYM","TEX","KCR","SFG","SDP","PHI","MIA"], positions: ["RF"], seasons: range(2005,2016) },
  { name: "Michael Cuddyer", teams: ["MIN","COL","NYM"], positions: ["RF","1B","2B","3B"], seasons: range(2001,2015) },
  { name: "Xavier Nady", teams: ["SDP","NYM","PIT","NYY","CHC","ARI","SFG","WSN"], positions: ["RF","LF"], seasons: range(2000,2013) },
  { name: "Ichiro Suzuki", teams: ["SEA","NYY","MIA"], positions: ["RF","CF"], seasons: range(2001,2019) },
  { name: "Sammy Sosa", teams: ["TEX","CHW","CHC","BAL"], positions: ["RF","CF"], seasons: range(1989,2007) },
  { name: "Gary Sheffield", teams: ["MIL","SDP","FLA","LAD","ATL","NYY","DET","NYM"], positions: ["RF","LF","3B"], seasons: range(1988,2009) },
  { name: "Paul O'Neill", teams: ["CIN","NYY"], positions: ["RF","LF"], seasons: range(1985,2001) },
  { name: "Ruben Sierra", teams: ["TEX","OAK","NYY","DET","CIN","TOR","SEA","TOR","NYY","MIN","TEX"], positions: ["RF","DH"], seasons: range(1986,2006) },
  { name: "Jose Cruz Jr.", teams: ["SEA","TOR","ARI","ATL","TB"], positions: ["RF","CF"], seasons: range(1997,2008) },
  { name: "Dave Parker", teams: ["PIT","CIN","OAK","MIL","CAL","TOR"], positions: ["RF","LF"], seasons: range(1973,1991) },
  { name: "Andre Dawson", teams: ["MON","CHC","BOS","FLA"], positions: ["CF","RF"], seasons: range(1976,1996) },
  { name: "Darryl Strawberry", teams: ["NYM","LAD","SFG","NYY"], positions: ["RF","LF"], seasons: range(1983,1999) },
  { name: "Dave Winfield", teams: ["SDP","NYY","CAL","ANA","TOR","MIN","CLE"], positions: ["RF","LF","DH"], seasons: range(1973,1995) },
  { name: "Shawn Green", teams: ["TOR","LAD","ARI","NYM"], positions: ["RF","CF","LF"], seasons: range(1993,2007) },
  { name: "Jesse Barfield", teams: ["TOR","NYY"], positions: ["RF"], seasons: range(1981,1992) },
  { name: "Dwight Evans", teams: ["BOS","BAL"], positions: ["RF"], seasons: range(1972,1991) },
  { name: "Cody Bellinger", teams: ["LAD","CHC","NYY"], positions: ["CF","RF","1B"], seasons: range(2017,2024) },
  { name: "Kyle Tucker", teams: ["HOU","CHC"], positions: ["RF","LF"], seasons: range(2018,2024) },
  { name: "Seiya Suzuki", teams: ["CHC"], positions: ["RF"], seasons: range(2022,2024) },
  { name: "Lars Nootbaar", teams: ["STL"], positions: ["RF","CF","LF"], seasons: range(2021,2024) },
  { name: "Jesse Winker", teams: ["CIN","SEA","MIL","NYM","WSN"], positions: ["LF","RF"], seasons: range(2017,2024) },
  { name: "Tyler O'Neill", teams: ["STL","BOS"], positions: ["LF","CF","RF"], seasons: range(2018,2024) },
  { name: "Teoscar Hernandez", teams: ["HOU","TOR","SEA","LAD"], positions: ["RF","LF"], seasons: range(2017,2024) },
  { name: "Michael Conforto", teams: ["NYM","SFG"], positions: ["RF","CF","LF"], seasons: range(2015,2023) },
  { name: "Jake Marisnick", teams: ["FLA","MIA","HOU","NYM","CHC","SDP"], positions: ["CF","RF"], seasons: range(2013,2021) },
  { name: "Robbie Grossman", teams: ["HOU","OAK","MIN","DET","ATL","TEX"], positions: ["LF","RF","CF"], seasons: range(2013,2022) },
  { name: "Bryan Reynolds", teams: ["PIT"], positions: ["CF","LF","RF"], seasons: range(2019,2024) },

  // ─── DESIGNATED HITTERS (primarily) ──────────────────────────────────────
  { name: "Shohei Ohtani", teams: ["LAA","LAD"], positions: ["SP","DH","LF"], seasons: range(2018,2024) },
  { name: "Edgar Martinez", teams: ["SEA"], positions: ["3B","DH","1B"], seasons: range(1987,2004) },
  { name: "Harold Baines", teams: ["CHW","TEX","OAK","BAL","CLE"], positions: ["RF","DH"], seasons: range(1980,2001) },
  { name: "Paul Molitor", teams: ["MIL","TOR","MIN"], positions: ["3B","2B","DH","1B"], seasons: range(1978,1998) },
  { name: "Don Baylor", teams: ["BAL","OAK","CAL","NYY","BOS","MIN","TOR"], positions: ["LF","DH"], seasons: range(1970,1988) },
  { name: "Hal McRae", teams: ["CIN","KCR"], positions: ["LF","DH"], seasons: range(1968,1987) },
  { name: "Chili Davis", teams: ["SFG","CAL","ANA","MIN","KCR","NYY"], positions: ["LF","DH"], seasons: range(1981,1999) },
  { name: "Jose Canseco", teams: ["OAK","TEX","BOS","TOR","TBR","NYY"], positions: ["RF","DH"], seasons: range(1985,2001) },
  { name: "Kirk Gibson", teams: ["DET","LAD","KCR","PIT","DET"], positions: ["LF","RF","DH"], seasons: range(1979,1995) },
  { name: "Kendrys Morales", teams: ["ANA","LAA","SEA","MIN","KCR","TOR","OAK"], positions: ["1B","DH"], seasons: range(2006,2019) },
  { name: "Victor Martinez", teams: ["CLE","BOS","DET"], positions: ["C","1B","DH"], seasons: range(2002,2017) },
  { name: "Travis Hafner", teams: ["TEX","CLE","NYY"], positions: ["1B","DH"], seasons: range(2002,2013) },
  { name: "Jim Thome", teams: ["CLE","PHI","CHW","MIN","LAD"], positions: ["1B","3B","DH"], seasons: range(1991,2012) },
  { name: "Billy Butler", teams: ["KCR","OAK","NYY"], positions: ["1B","DH"], seasons: range(2007,2016) },
  { name: "Adam Lind", teams: ["TOR","MIL","SEA","WSN"], positions: ["1B","DH","LF"], seasons: range(2006,2017) },
  { name: "Dioner Navarro", teams: ["LAD","TBR","SEA","CHC","TOR"], positions: ["C","DH"], seasons: range(2004,2015) },
  { name: "Corey Hart", teams: ["MIL","SEA"], positions: ["RF","DH","1B"], seasons: range(2004,2015) },
  { name: "Jason Giambi", teams: ["OAK","NYY","COL","CLE"], positions: ["1B","DH"], seasons: range(1995,2014) },
  { name: "J.D. Martinez", teams: ["HOU","DET","ARI","BOS","NYM","LAD"], positions: ["RF","DH","LF"], seasons: range(2011,2024) },
  { name: "Nelson Cruz", teams: ["MIL","TEX","BAL","SEA","MIN","TBR","WSN","SDP"], positions: ["RF","DH"], seasons: range(2005,2022) },
  { name: "Michael Brantley", teams: ["CLE","HOU"], positions: ["LF","DH"], seasons: range(2009,2022) },
  { name: "Khris Davis", teams: ["MIL","OAK","TEX"], positions: ["LF","DH"], seasons: range(2013,2021) },

  // ─── STARTING PITCHERS ───────────────────────────────────────────────────
  { name: "Roger Clemens", teams: ["BOS","TOR","HOU","NYY"], positions: ["SP"], seasons: range(1984,2007) },
  { name: "Greg Maddux", teams: ["CHC","ATL","LAD","SDP"], positions: ["SP"], seasons: range(1986,2008) },
  { name: "Randy Johnson", teams: ["MON","SEA","HOU","ARI","NYY","SFG"], positions: ["SP"], seasons: range(1988,2009) },
  { name: "Pedro Martinez", teams: ["LAD","MON","BOS","NYM","PHI"], positions: ["SP"], seasons: range(1992,2009) },
  { name: "Nolan Ryan", teams: ["NYM","CAL","HOU","TEX"], positions: ["SP"], seasons: range(1966,1993) },
  { name: "Tom Seaver", teams: ["NYM","CIN","CHW","BOS"], positions: ["SP"], seasons: range(1967,1986) },
  { name: "Sandy Koufax", teams: ["BRO","LAD"], positions: ["SP"], seasons: range(1955,1966) },
  { name: "Bert Blyleven", teams: ["MIN","TEX","PIT","CLE","CAL"], positions: ["SP"], seasons: range(1970,1992) },
  { name: "Jack Morris", teams: ["DET","MIN","TOR","CLE"], positions: ["SP"], seasons: range(1977,1994) },
  { name: "Frank Viola", teams: ["MIN","NYM","BOS","TOR","CIN"], positions: ["SP"], seasons: range(1982,1996) },
  { name: "John Smoltz", teams: ["ATL","BOS","STL","DET"], positions: ["SP","RP"], seasons: range(1988,2009) },
  { name: "Tom Glavine", teams: ["ATL","NYM"], positions: ["SP"], seasons: range(1987,2008) },
  { name: "Greg Maddux", teams: ["CHC","ATL","LAD","SDP"], positions: ["SP"], seasons: range(1986,2008) },
  { name: "Curt Schilling", teams: ["BAL","HOU","PHI","ARI","BOS"], positions: ["SP"], seasons: range(1988,2008) },
  { name: "Mike Mussina", teams: ["BAL","NYY"], positions: ["SP"], seasons: range(1991,2008) },
  { name: "Roy Halladay", teams: ["TOR","PHI"], positions: ["SP"], seasons: range(1998,2013) },
  { name: "Roy Oswalt", teams: ["HOU","PHI","TEX","COL"], positions: ["SP"], seasons: range(2001,2013) },
  { name: "Johan Santana", teams: ["MIN","NYM"], positions: ["SP"], seasons: range(2000,2012) },
  { name: "CC Sabathia", teams: ["CLE","MIL","NYY"], positions: ["SP"], seasons: range(2001,2019) },
  { name: "Felix Hernandez", teams: ["SEA"], positions: ["SP"], seasons: range(2005,2019) },
  { name: "Justin Verlander", teams: ["DET","HOU","NYM","TOR"], positions: ["SP"], seasons: range(2005,2024) },
  { name: "Max Scherzer", teams: ["ARI","DET","WSN","LAD","NYM","TEX"], positions: ["SP"], seasons: range(2008,2023) },
  { name: "Clayton Kershaw", teams: ["LAD"], positions: ["SP"], seasons: range(2008,2024) },
  { name: "Zack Greinke", teams: ["KCR","MIL","LAD","ARI","HOU"], positions: ["SP"], seasons: range(2004,2023) },
  { name: "Chris Carpenter", teams: ["TOR","STL"], positions: ["SP"], seasons: range(1997,2012) },
  { name: "Adam Wainwright", teams: ["STL"], positions: ["SP","RP"], seasons: range(2005,2023) },
  { name: "Madison Bumgarner", teams: ["SFG","ARI"], positions: ["SP"], seasons: range(2009,2023) },
  { name: "Stephen Strasburg", teams: ["WSN"], positions: ["SP"], seasons: range(2010,2023) },
  { name: "Jacob deGrom", teams: ["NYM","TEX"], positions: ["SP"], seasons: range(2014,2024) },
  { name: "Gerrit Cole", teams: ["PIT","HOU","NYY"], positions: ["SP"], seasons: range(2013,2024) },
  { name: "Blake Snell", teams: ["TBR","SDP","SFG"], positions: ["SP"], seasons: range(2016,2024) },
  { name: "Corbin Burnes", teams: ["MIL","BAL"], positions: ["SP"], seasons: range(2018,2024) },
  { name: "Shane Bieber", teams: ["CLE"], positions: ["SP"], seasons: range(2018,2024) },
  { name: "Kevin Gausman", teams: ["BAL","ATL","CIN","SFG","TOR"], positions: ["SP"], seasons: range(2013,2024) },
  { name: "Aaron Nola", teams: ["PHI"], positions: ["SP"], seasons: range(2015,2024) },
  { name: "Luis Castillo", teams: ["CIN","SEA"], positions: ["SP"], seasons: range(2017,2024) },
  { name: "Framber Valdez", teams: ["HOU"], positions: ["SP"], seasons: range(2019,2024) },
  { name: "Sandy Alcantara", teams: ["STL","MIA"], positions: ["SP"], seasons: range(2017,2024) },
  { name: "Freddy Peralta", teams: ["MIL"], positions: ["SP","RP"], seasons: range(2018,2024) },
  { name: "Jose Berrios", teams: ["MIN","TOR"], positions: ["SP"], seasons: range(2016,2024) },
  { name: "Pablo Lopez", teams: ["MIA","MIN"], positions: ["SP"], seasons: range(2018,2024) },
  { name: "David Price", teams: ["TBR","DET","TOR","BOS","LAD"], positions: ["SP"], seasons: range(2008,2022) },
  { name: "Cliff Lee", teams: ["CLE","SEA","TEX","PHI"], positions: ["SP"], seasons: range(2002,2014) },
  { name: "Tim Lincecum", teams: ["SFG"], positions: ["SP"], seasons: range(2007,2016) },
  { name: "Jake Peavy", teams: ["SDP","CHW","BOS","SFG"], positions: ["SP"], seasons: range(2002,2016) },
  { name: "Cole Hamels", teams: ["PHI","TEX","CHC","ATL"], positions: ["SP"], seasons: range(2006,2020) },
  { name: "Jon Lester", teams: ["BOS","OAK","CHC","STL","WSN","PIT"], positions: ["SP"], seasons: range(2006,2021) },
  { name: "Jake Arrieta", teams: ["BAL","CHC","PHI"], positions: ["SP"], seasons: range(2010,2020) },
  { name: "Chris Sale", teams: ["CHW","BOS","ATL"], positions: ["SP","RP"], seasons: range(2010,2024) },
  { name: "David Robertson", teams: ["NYY","CHW","PHI","CHC","COL"], positions: ["RP"], seasons: range(2008,2023) },
  { name: "Ervin Santana", teams: ["ANA","LAA","KCR","ATL","MIN"], positions: ["SP"], seasons: range(2005,2018) },
  { name: "James Shields", teams: ["TBR","KCR","SDP","CHW"], positions: ["SP"], seasons: range(2006,2018) },
  { name: "Trevor Bauer", teams: ["ARI","CLE","CIN","LAD"], positions: ["SP"], seasons: range(2012,2021) },
  { name: "Gio Gonzalez", teams: ["OAK","WSN","MIL","CHW","NYY"], positions: ["SP"], seasons: range(2008,2019) },
  { name: "Mike Minor", teams: ["ATL","KCR","TEX","OAK","CIN"], positions: ["SP","RP"], seasons: range(2010,2022) },
  { name: "Lance Lynn", teams: ["STL","NYY","TEX","CHW","LAD","STL"], positions: ["SP"], seasons: range(2011,2024) },
  { name: "Masahiro Tanaka", teams: ["NYY"], positions: ["SP"], seasons: range(2014,2020) },
  { name: "Rich Hill", teams: ["CHC","BAL","BOS","OAK","LAD","MIN","NYM","TBR","TEX","PIT"], positions: ["SP"], seasons: range(2005,2022) },
  { name: "Kyle Hendricks", teams: ["CHC"], positions: ["SP"], seasons: range(2014,2024) },
  { name: "Carlos Rodon", teams: ["CHW","SFG","NYY"], positions: ["SP"], seasons: range(2015,2024) },
  { name: "Logan Webb", teams: ["SFG"], positions: ["SP"], seasons: range(2019,2024) },
  { name: "Zac Gallen", teams: ["MIA","ARI"], positions: ["SP"], seasons: range(2019,2024) },
  { name: "Tony Gonsolin", teams: ["LAD"], positions: ["SP"], seasons: range(2019,2024) },
  { name: "Joe Musgrove", teams: ["HOU","PIT","SDP"], positions: ["SP"], seasons: range(2016,2024) },
  { name: "Nestor Cortes", teams: ["NYY","BAL","SEA"], positions: ["SP","RP"], seasons: range(2018,2024) },
  { name: "Kyle Gibson", teams: ["MIN","TEX","PHI","BAL","STL"], positions: ["SP"], seasons: range(2013,2024) },
  { name: "Nathan Eovaldi", teams: ["NYY","MIA","LAD","BOS","TEX"], positions: ["SP"], seasons: range(2011,2024) },
  { name: "Sonny Gray", teams: ["OAK","NYY","CIN","MIN","STL"], positions: ["SP"], seasons: range(2013,2024) },
  { name: "Tyler Glasnow", teams: ["PIT","TBR","LAD"], positions: ["SP"], seasons: range(2016,2024) },
  { name: "Spencer Strider", teams: ["ATL"], positions: ["SP","RP"], seasons: range(2022,2024) },
  { name: "Kodai Senga", teams: ["NYM"], positions: ["SP"], seasons: range(2023,2024) },
  { name: "Tarik Skubal", teams: ["DET"], positions: ["SP"], seasons: range(2020,2024) },
  { name: "Hunter Greene", teams: ["CIN"], positions: ["SP"], seasons: range(2022,2024) },
  { name: "Paul Skenes", teams: ["PIT"], positions: ["SP"], seasons: range(2024,2024) },
  { name: "Dwight Gooden", teams: ["NYM","CLE","NYY","HOU","TBR"], positions: ["SP"], seasons: range(1984,2000) },
  { name: "Orel Hershiser", teams: ["LAD","CLE","SFG","NYM"], positions: ["SP"], seasons: range(1983,2000) },
  { name: "Bret Saberhagen", teams: ["KCR","NYM","COL","BOS"], positions: ["SP"], seasons: range(1984,2001) },
  { name: "Dave Stieb", teams: ["TOR","CHW","STL"], positions: ["SP"], seasons: range(1979,1998) },
  { name: "Jimmy Key", teams: ["TOR","NYY","BAL","CLE"], positions: ["SP"], seasons: range(1984,1998) },
  { name: "Bud Black", teams: ["KCR","CLE","TOR","SFG"], positions: ["SP"], seasons: range(1981,1995) },
  { name: "Chuck Finley", teams: ["CAL","ANA","CLE","STL"], positions: ["SP"], seasons: range(1986,2002) },
  { name: "Bob Welch", teams: ["LAD","OAK"], positions: ["SP"], seasons: range(1978,1994) },
  { name: "Bill Swift", teams: ["SEA","SFG","COL"], positions: ["SP"], seasons: range(1985,1998) },
  { name: "Andy Pettitte", teams: ["NYY","HOU"], positions: ["SP"], seasons: range(1995,2013) },
  { name: "Kevin Brown", teams: ["TEX","BAL","FLA","SDP","LAD","NYY"], positions: ["SP"], seasons: range(1986,2005) },
  { name: "David Cone", teams: ["KCR","NYM","TOR","NYY","BOS"], positions: ["SP"], seasons: range(1986,2003) },
  { name: "David Wells", teams: ["TOR","DET","CIN","BAL","NYY","CHW","BOS","SDP","NYM","LAD"], positions: ["SP"], seasons: range(1987,2007) },
  { name: "Jon Garland", teams: ["CHW","LAA","ARI","COL","SDP"], positions: ["SP"], seasons: range(2000,2011) },
  { name: "Carlos Zambrano", teams: ["CHC","MIA"], positions: ["SP"], seasons: range(2001,2012) },
  { name: "Ted Lilly", teams: ["OAK","TOR","CHC","LAD"], positions: ["SP"], seasons: range(1999,2012) },
  { name: "Mark Buehrle", teams: ["CHW","MIA","TOR"], positions: ["SP"], seasons: range(2000,2015) },
  { name: "Erik Bedard", teams: ["BAL","SEA","PIT","LAD","BOS","HOU"], positions: ["SP"], seasons: range(2002,2013) },
  { name: "Javier Vazquez", teams: ["MON","NYY","ARI","CHW","ATL","NYY","FLA"], positions: ["SP"], seasons: range(1998,2011) },
  { name: "Brad Radke", teams: ["MIN"], positions: ["SP"], seasons: range(1995,2006) },
  { name: "Kelvim Escobar", teams: ["TOR","ANA","LAA"], positions: ["SP","RP"], seasons: range(1997,2008) },
  { name: "Livan Hernandez", teams: ["FLA","SFG","MON","WSN","ARI","COL","NYM","OAK","ATL","MIL","HOU"], positions: ["SP"], seasons: range(1996,2012) },
  { name: "Tim Hudson", teams: ["OAK","ATL","SFG"], positions: ["SP"], seasons: range(1999,2015) },
  { name: "Barry Zito", teams: ["OAK","SFG"], positions: ["SP"], seasons: range(2000,2015) },
  { name: "Matt Cain", teams: ["SFG"], positions: ["SP"], seasons: range(2005,2017) },
  { name: "Brett Myers", teams: ["PHI","HOU","CHW","CLE"], positions: ["SP","RP"], seasons: range(2002,2012) },
  { name: "Russ Ortiz", teams: ["SFG","ATL","ARI","BAL","HOU"], positions: ["SP"], seasons: range(1998,2009) },
  { name: "Rodrigo Lopez", teams: ["SDP","BAL","COL","ARI","PHI"], positions: ["SP"], seasons: range(2000,2010) },
  { name: "Vicente Padilla", teams: ["PHI","TEX","LAD","BOS"], positions: ["SP"], seasons: range(1999,2012) },
  { name: "Freddy Garcia", teams: ["SEA","CHW","PHI","DET","NYY"], positions: ["SP"], seasons: range(1999,2013) },
  { name: "Matt Morris", teams: ["STL","SFG","PIT"], positions: ["SP"], seasons: range(1997,2008) },
  { name: "Jose Lima", teams: ["HOU","DET","KCR","LAD","NYM"], positions: ["SP"], seasons: range(1994,2006) },
  { name: "Kirk Rueter", teams: ["MON","SFG"], positions: ["SP"], seasons: range(1993,2005) },
  { name: "Brad Penny", teams: ["FLA","MIA","LAD","BOS","STL","SFG","DET"], positions: ["SP"], seasons: range(2000,2012) },
  { name: "Jeff Weaver", teams: ["DET","NYY","LAD","STL","ANA","SEA"], positions: ["SP"], seasons: range(1999,2007) },
  { name: "Aaron Sele", teams: ["BOS","TEX","SEA","ANA","LAD","NYM"], positions: ["SP"], seasons: range(1993,2007) },
  { name: "Sidney Ponson", teams: ["BAL","SFG","STL","NYY","MIN","KCR"], positions: ["SP"], seasons: range(1998,2011) },
  { name: "Kevin Appier", teams: ["KCR","OAK","NYM","ANA"], positions: ["SP"], seasons: range(1989,2004) },
  { name: "Denny Neagle", teams: ["MIN","PIT","ATL","CIN","NYY","COL"], positions: ["SP"], seasons: range(1991,2003) },
  { name: "Tom Candiotti", teams: ["MIL","CLE","TOR","LAD","OAK"], positions: ["SP"], seasons: range(1983,1999) },
  { name: "Steve Rogers", teams: ["MON"], positions: ["SP"], seasons: range(1973,1985) },
  { name: "Bob Tewksbury", teams: ["NYY","CHC","STL","TEX","SDP","MIN"], positions: ["SP"], seasons: range(1986,1998) },
  { name: "Doyle Alexander", teams: ["BAL","NYY","TEX","ATL","MON","SFG","TOR","DET"], positions: ["SP"], seasons: range(1971,1989) },
  { name: "Charlie Leibrandt", teams: ["CIN","KCR","ATL","TEX"], positions: ["SP"], seasons: range(1979,1993) },
  { name: "Frank Tanana", teams: ["CAL","BOS","TEX","DET","NYM","NYY"], positions: ["SP"], seasons: range(1973,1993) },
  { name: "Mike Flanagan", teams: ["BAL","TOR"], positions: ["SP"], seasons: range(1975,1992) },
  { name: "Dennis Martinez", teams: ["BAL","MON","CLE","ATL","SEA","NYM"], positions: ["SP"], seasons: range(1976,1998) },
  { name: "Scott McGregor", teams: ["BAL"], positions: ["SP"], seasons: range(1976,1988) },
  { name: "Mike Boddicker", teams: ["BAL","BOS","KCR","MIL"], positions: ["SP"], seasons: range(1980,1993) },
  { name: "Storm Davis", teams: ["BAL","SDP","OAK","KCR","DET","NYY","STL"], positions: ["SP"], seasons: range(1982,1994) },
  { name: "Dwight Evans", teams: ["BOS","BAL"], positions: ["RF"], seasons: range(1972,1991) },
  { name: "Bob Ojeda", teams: ["BOS","NYM","LAD","CLE"], positions: ["SP"], seasons: range(1980,1994) },
  { name: "Bruce Hurst", teams: ["BOS","SDP","COL"], positions: ["SP"], seasons: range(1980,1994) },
  { name: "Oil Can Boyd", teams: ["BOS","MON","TEX"], positions: ["SP"], seasons: range(1982,1991) },
  { name: "Ron Darling", teams: ["NYM","MON","OAK"], positions: ["SP"], seasons: range(1983,1995) },
  { name: "Sid Fernandez", teams: ["LAD","NYM","BAL","PHI","HOU"], positions: ["SP"], seasons: range(1983,1997) },
  { name: "Bob Knepper", teams: ["SFG","HOU","TEX"], positions: ["SP"], seasons: range(1976,1990) },
  { name: "Rick Reuschel", teams: ["CHC","PIT","NYY","SFG"], positions: ["SP"], seasons: range(1972,1991) },
  { name: "Mike Krukow", teams: ["CHC","PHI","SFG"], positions: ["SP"], seasons: range(1976,1989) },
  { name: "Rick Sutcliffe", teams: ["LAD","CLE","CHC","BAL","STL"], positions: ["SP"], seasons: range(1976,1994) },
  { name: "Scott Sanderson", teams: ["MON","CHC","OAK","NYY","CAL","SFG","CHW"], positions: ["SP"], seasons: range(1978,1996) },
  { name: "Mike Scott", teams: ["NYM","HOU"], positions: ["SP"], seasons: range(1979,1991) },
  { name: "Bob Knepper", teams: ["SFG","HOU","TEX"], positions: ["SP"], seasons: range(1976,1990) },
  { name: "Jim Clancy", teams: ["TOR","HOU","ATL"], positions: ["SP"], seasons: range(1977,1992) },
  { name: "Dennis Eckersley", teams: ["CLE","BOS","CHC","OAK","STL"], positions: ["SP","RP"], seasons: range(1975,1998) },
  { name: "Burt Hooton", teams: ["CHC","LAD","TEX"], positions: ["SP"], seasons: range(1971,1985) },
  { name: "John Denny", teams: ["STL","CLE","PHI","CIN"], positions: ["SP"], seasons: range(1974,1986) },
  { name: "Joaquin Andujar", teams: ["HOU","STL","OAK"], positions: ["SP"], seasons: range(1976,1988) },
  { name: "Pascual Perez", teams: ["PIT","ATL","MON","NYY"], positions: ["SP"], seasons: range(1980,1991) },
  { name: "Dave Righetti", teams: ["NYY","SFG","OAK","TOR","CHW"], positions: ["SP","RP"], seasons: range(1979,1995) },

  // ─── RELIEF PITCHERS ─────────────────────────────────────────────────────
  { name: "Mariano Rivera", teams: ["NYY"], positions: ["RP"], seasons: range(1995,2013) },
  { name: "Trevor Hoffman", teams: ["FLA","MIA","SDP","MIL"], positions: ["RP"], seasons: range(1993,2010) },
  { name: "Dennis Eckersley", teams: ["CLE","BOS","CHC","OAK","STL"], positions: ["SP","RP"], seasons: range(1975,1998) },
  { name: "Lee Smith", teams: ["CHC","BOS","STL","NYY","BAL","CAL","CIN","MON"], positions: ["RP"], seasons: range(1980,1997) },
  { name: "John Franco", teams: ["CIN","NYM"], positions: ["RP"], seasons: range(1984,2005) },
  { name: "Rollie Fingers", teams: ["OAK","SDP","MIL"], positions: ["RP"], seasons: range(1968,1985) },
  { name: "Rich Gossage", teams: ["CHW","PIT","NYY","SDP","CHC","SFG","TEX","OAK","SEA"], positions: ["RP"], seasons: range(1972,1994) },
  { name: "Bruce Sutter", teams: ["CHC","STL","ATL"], positions: ["RP"], seasons: range(1976,1988) },
  { name: "Billy Wagner", teams: ["HOU","PHI","NYM","BOS","ATL"], positions: ["RP"], seasons: range(1995,2010) },
  { name: "Eric Gagne", teams: ["LAD","TEX","BOS","MIL"], positions: ["RP","SP"], seasons: range(1999,2008) },
  { name: "Aroldis Chapman", teams: ["CIN","NYY","CHC","KCR","TEX","PIT"], positions: ["RP"], seasons: range(2010,2024) },
  { name: "Craig Kimbrel", teams: ["ATL","SDP","BOS","CHC","CHW","LAD","PHI"], positions: ["RP"], seasons: range(2010,2024) },
  { name: "Kenley Jansen", teams: ["LAD","ATL","BOS","TOR","HOU"], positions: ["RP"], seasons: range(2010,2024) },
  { name: "Robb Nen", teams: ["TEX","FLA","MIA","SFG"], positions: ["RP"], seasons: range(1993,2002) },
  { name: "John Wetteland", teams: ["LAD","MON","NYY","TEX"], positions: ["RP"], seasons: range(1989,2000) },
  { name: "Jeff Reardon", teams: ["NYM","MON","MIN","BOS","ATL","CIN","NYY","PIT"], positions: ["RP"], seasons: range(1979,1994) },
  { name: "Rod Beck", teams: ["SFG","CHC","BOS","SDP"], positions: ["RP"], seasons: range(1991,2004) },
  { name: "Jose Mesa", teams: ["BAL","CLE","SFG","SEA","PHI","PIT"], positions: ["RP","SP"], seasons: range(1987,2007) },
  { name: "Tom Henke", teams: ["TEX","TOR","STL"], positions: ["RP"], seasons: range(1982,1995) },
  { name: "Jeff Montgomery", teams: ["CIN","KCR"], positions: ["RP"], seasons: range(1987,1999) },
  { name: "Randy Myers", teams: ["NYM","CIN","SDP","CHC","BAL","TOR"], positions: ["RP"], seasons: range(1985,1998) },
  { name: "Greg Olson", teams: ["MIN","ATL","NYM"], positions: ["C","RP"], seasons: range(1989,1996) },
  { name: "Jeff Nelson", teams: ["SEA","NYY","TEX","CHW"], positions: ["RP"], seasons: range(1992,2006) },
  { name: "Mike Stanton", teams: ["HOU","ATL","BOS","NYY","SFG","WSN","MIN","CIN"], positions: ["RP"], seasons: range(1989,2006) },
  { name: "Arthur Rhodes", teams: ["BAL","SEA","CIN","OAK","PHI","STL","CLE","FLA","TEX"], positions: ["RP"], seasons: range(1991,2011) },
  { name: "Mike Timlin", teams: ["TOR","SEA","STL","BAL","PHI","BOS"], positions: ["RP"], seasons: range(1991,2008) },
  { name: "Paul Assenmacher", teams: ["ATL","CHC","NYY","CHW","CLE"], positions: ["RP"], seasons: range(1986,1999) },
  { name: "Duane Ward", teams: ["ATL","TOR"], positions: ["RP"], seasons: range(1986,1995) },
  { name: "Bob Wickman", teams: ["NYY","CHW","MIL","CLE","ATL"], positions: ["RP"], seasons: range(1992,2006) },
  { name: "Dan Plesac", teams: ["MIL","CHC","PIT","TOR","ARI","PHI"], positions: ["RP"], seasons: range(1986,2003) },
  { name: "Todd Worrell", teams: ["STL","LAD"], positions: ["RP"], seasons: range(1985,1997) },
  { name: "Dave Smith", teams: ["HOU","CHC"], positions: ["RP"], seasons: range(1980,1992) },
  { name: "John Hiller", teams: ["DET"], positions: ["RP","SP"], seasons: range(1965,1980) },
  { name: "Kent Tekulve", teams: ["PIT","PHI","CIN"], positions: ["RP"], seasons: range(1974,1989) },
  { name: "Doug Jones", teams: ["MIL","CLE","HOU","PHI","CHC","OAK"], positions: ["RP"], seasons: range(1982,2000) },
  { name: "Mike Jackson", teams: ["PHI","SEA","SFG","CIN","CLE","HOU","MIN"], positions: ["RP"], seasons: range(1986,2004) },
  { name: "Gregg Olson", teams: ["BAL","ATL","CLE","DET","HOU","ARI","KCR","LAD"], positions: ["RP"], seasons: range(1988,2001) },
  { name: "Dan Quisenberry", teams: ["KCR","STL","SFG"], positions: ["RP"], seasons: range(1979,1990) },
  { name: "Sparky Lyle", teams: ["BOS","NYY","TEX","PHI","CHW"], positions: ["RP"], seasons: range(1967,1982) },
  { name: "Tug McGraw", teams: ["NYM","PHI"], positions: ["RP","SP"], seasons: range(1965,1984) },
  { name: "Mike Marshall", teams: ["SEA","CHC","MON","LAD","ATL","TEX","MIN","NYM"], positions: ["RP"], seasons: range(1967,1981) },
  { name: "Francisco Rodriguez", teams: ["ANA","LAA","NYM","MIL","DET","BAL","CHC"], positions: ["RP"], seasons: range(2002,2017) },
  { name: "Jonathan Papelbon", teams: ["BOS","PHI","WSN","PIT"], positions: ["RP"], seasons: range(2005,2017) },
  { name: "Joe Nathan", teams: ["SFG","MIN","TEX","DET"], positions: ["RP"], seasons: range(1999,2016) },
  { name: "Brad Lidge", teams: ["HOU","PHI","WSN"], positions: ["RP"], seasons: range(2002,2012) },
  { name: "Jason Isringhausen", teams: ["NYM","OAK","STL","TBR","PIT","ATL"], positions: ["RP","SP"], seasons: range(1995,2012) },
  { name: "BJ Ryan", teams: ["BAL","TOR"], positions: ["RP"], seasons: range(1999,2008) },
  { name: "Tom Gordon", teams: ["KCR","BOS","CHC","HOU","NYY","PHI","ARI"], positions: ["RP","SP"], seasons: range(1988,2009) },
  { name: "Keith Foulke", teams: ["CHW","OAK","BOS","CLE","PHI"], positions: ["RP"], seasons: range(1997,2008) },
  { name: "Fernando Rodney", teams: ["DET","LAA","SEA","TBR","ARI","CHC","MIA","OAK","MIN"], positions: ["RP"], seasons: range(2002,2019) },
  { name: "Joakim Soria", teams: ["KCR","DET","TEX","PIT","OAK","CHW"], positions: ["RP"], seasons: range(2007,2021) },
  { name: "Andrew Bailey", teams: ["OAK","BOS","LAA","NYY"], positions: ["RP"], seasons: range(2009,2017) },
  { name: "Sergio Romo", teams: ["SFG","LAD","TBR","MIA","MIN"], positions: ["RP"], seasons: range(2008,2021) },
  { name: "Rafael Soriano", teams: ["ATL","SEA","TBR","NYY","WSN"], positions: ["RP"], seasons: range(2003,2015) },
  { name: "Greg Holland", teams: ["KCR","COL","STL","WSN","ARI","MIA"], positions: ["RP"], seasons: range(2010,2020) },
  { name: "Carson Smith", teams: ["SEA","BOS"], positions: ["RP"], seasons: range(2014,2021) },
  { name: "Zach Britton", teams: ["BAL","NYY"], positions: ["RP","SP"], seasons: range(2011,2022) },
  { name: "Roberto Osuna", teams: ["TOR","HOU","TEX"], positions: ["RP"], seasons: range(2015,2021) },
  { name: "Andrew Miller", teams: ["DET","BOS","NYY","CLE","STL","CHW"], positions: ["RP","SP"], seasons: range(2006,2020) },
  { name: "Wade Davis", teams: ["TBR","KCR","CHC","COL"], positions: ["RP","SP"], seasons: range(2009,2020) },
  { name: "Dellin Betances", teams: ["NYY","NYM"], positions: ["RP"], seasons: range(2011,2021) },
  { name: "Tony Watson", teams: ["PIT","SFG","LAA","ATL"], positions: ["RP"], seasons: range(2011,2021) },
  { name: "Alex Colome", teams: ["TBR","CHW","MIN","COL"], positions: ["RP"], seasons: range(2013,2021) },
  { name: "Edwin Diaz", teams: ["SEA","NYM"], positions: ["RP"], seasons: range(2016,2024) },
  { name: "Ryan Pressly", teams: ["MIN","HOU"], positions: ["RP"], seasons: range(2013,2024) },
  { name: "Josh Hader", teams: ["MIL","SDP"], positions: ["RP"], seasons: range(2017,2024) },
  { name: "Emmanuel Clase", teams: ["TEX","CLE"], positions: ["RP"], seasons: range(2019,2024) },
  { name: "Devin Williams", teams: ["MIL"], positions: ["RP"], seasons: range(2020,2024) },
  { name: "Clay Holmes", teams: ["PIT","NYY"], positions: ["RP"], seasons: range(2018,2024) },
  { name: "Alexis Diaz", teams: ["CIN"], positions: ["RP"], seasons: range(2022,2024) },
  { name: "Evan Phillips", teams: ["BAL","HOU","LAD"], positions: ["RP"], seasons: range(2019,2024) },
  { name: "Ryan Helsley", teams: ["STL"], positions: ["RP"], seasons: range(2019,2024) },
  { name: "Jordan Romano", teams: ["TOR"], positions: ["RP"], seasons: range(2019,2024) },
  { name: "Camilo Doval", teams: ["SFG"], positions: ["RP"], seasons: range(2021,2024) },
  { name: "Andres Munoz", teams: ["SDP","SEA"], positions: ["RP"], seasons: range(2019,2024) },
  { name: "Nick Martinez", teams: ["TEX","SDP"], positions: ["SP","RP"], seasons: range(2014,2024) },
  { name: "Kenley Jansen", teams: ["LAD","ATL","BOS","TOR","HOU"], positions: ["RP"], seasons: range(2010,2024) },
  { name: "Liam Hendriks", teams: ["MIN","TOR","OAK","CHW","BOS"], positions: ["RP"], seasons: range(2011,2023) },
  { name: "Taylor Rogers", teams: ["MIN","SDP","MIL","SFG"], positions: ["RP"], seasons: range(2016,2024) },
  { name: "Garrett Whitlock", teams: ["BOS"], positions: ["RP","SP"], seasons: range(2021,2024) },
  { name: "Pete Fairbanks", teams: ["TEX","TBR"], positions: ["RP"], seasons: range(2019,2024) },
  { name: "Dany Jimenez", teams: ["OAK","ARI"], positions: ["RP"], seasons: range(2022,2024) },
];

function range(start, end) {
  const arr = [];
  for (let y = start; y <= end; y++) arr.push(y);
  return arr;
}

// Deduplicate by name (some entries listed twice for different position notes)
const seen = new Map();
for (const p of players) {
  if (!seen.has(p.name)) {
    seen.set(p.name, p);
  }
}
const deduped = [...seen.values()];

// Convert to flat format: id, name, teams[], positions[], seasons[]
const output = deduped.map(p => {
  const id = p.name.toLowerCase()
    .replace(/[^a-z0-9 ]/g, '')
    .replace(/\s+/g, '-');
  const uniqueTeams = [...new Set(p.teams)];
  const uniquePositions = [...new Set(p.positions)];
  return {
    id,
    name: p.name,
    teams: uniqueTeams,
    positions: uniquePositions,
    seasons: p.seasons
  };
});

const fs = require('fs');
fs.writeFileSync(
  __dirname + '/../src/data/players.json',
  JSON.stringify(output, null, 2)
);
console.log('Written', output.length, 'players');
console.log('Teams:', new Set(output.flatMap(p => p.teams)).size);
console.log('Positions:', [...new Set(output.flatMap(p => p.positions))].sort().join(', '));
